### ISSUE TITLE
Review and gather feedback around latest form wireframes

### ISSUE THREAD

**Issue by UchMok** [18F/civil-rights#224]
## Definition of done
- [x] Present and get feedback from core team
- [x] Present and get feedback from IER + ELS [6/27]
- [x] Feedback from VOT + HCE [7/1]
- [x] Feedback from DRS  [Friday 6/28] - EOS ppt not in deep dives
- [x] Feedback from SPL + CRM + FCS [6/27] - FCS & CRM ppt not in deep dives
- [x] EOS
- [ ] SPL (legal)
- [ ] HCE (legal)
- [ ] VOT (maybe a follow up)
## Attachments
- [iNvision form experience](https://gsa.invisionapp.com/share/BPSQ5THWGZ6#/screens/370982162_What_-_A)
- [Form presentation for section walkthrough](https://docs.google.com/presentation/d/1y1cN2YFR30PtyXFKWlOCr81P-I_Bl_nQWzXT70gqqeM/edit#slide=id.g5c388ee689_0_838)

**Comment by UchMok** [comment]
from @Jacklynn : UX research on dropdown - they tend to be less usable, especially for long lists of unfamiliar items (types of respondents vs as opposed to country names) https://www.nngroup.com/articles/drop-down-menus/

**Comment by UchMok** [comment]
(for internal use only) https://web-silly-alligator.app.cloud.gov/form/1-fierce-flamingo

**Comment by UchMok** [comment]
@AvivaOskow to update the invision link on this card

**Comment by Jacklynn** [comment]
I can separate these out into smaller tasks
