### ISSUE TITLE
Follow up on section routing homework questions

### ISSUE THREAD

**Issue by UchMok** [18F/civil-rights#226]
## Follow up
- [ ] HCE - didn't complete the routing portion besides for Service Members. Would like to see how the bigger majority of their work is sorted
- [ ] SPL - Some confusion about how she filled out the diagram. I think she meant to indicate the state/local goes to SPL
- [ ] SPL- ask to be more specific about the logic. Only chose location, but know they don't have jurisdiction over all prison complaints
- [x] There was a pattern across sections of wanting to separate groups into their own line item, what value is there in doing this if they would get routed to the same place? Wondering if this is related to DRS' want for tagging in the system
- [x] EOS - where does something about a private school that isn't disability-related go?
- [ ] EOS - "national origin" - said should go to ELS but shouldn't it be IER?
- [x] ELS - why distinguish between [county, city or state federal government] and [Federal government]? Does that affect their routing?
- [ ] FBI - more detail around when things should get routed there
- [x] Synthesize results more
- [ ] EOS - is there anything else special we should do because of your audience. Ex: are minors allowed to submit a form?

## Section feedback to consider
- [x] Added the ability to indicate filing on behalf of another person
- [x] Testing grouping + example treatment in the form. May change depending on how the sections use it (q above)
- [x] Clarify different between sex, gender, and sexuality or combine?
- [x] Consider "Entity receiving federal funds or resources (federal land, property, detail of federal personnel)" -- too legal, precise?
- [x] add "when did the incident occur"

## Attachments
[Section routing feedback](https://docs.google.com/spreadsheets/d/12Xrum1alp_hwud1hK9QZoC-RglPBtxg3y0maF0JHyK8/edit#gid=0)

**Comment by Jacklynn** [comment]
We'll need a separate meeting for HCE, SPL, and CRM to understand their routing process
