### ISSUE TITLE
Acquire DOJ Acquia-hosted Drupal app

### ISSUE THREAD

**Issue by UchMok** [18F/civil-rights#232]
## Definition of done
- [x] Acquia to create DOJ sandbox environment by June 21
- [x] Get access to file support tickets from Acquia
- [ ] @LindsayYoung  @darrenwechsler1 to test if Acquia app is viable framework for development

## Attachments
[title](URL)

**Comment by UchMok** [comment]
Updates from yesterday's meeting w/ Acquia:

They're eager to be support for our team
They provided a sandbox, but we may have run into firewall rule blockers

**Comment by LindsayYoung** [comment]
I think this is a duplicate of https://github.com/18F/crt-portal/issues/4 (that is done too)
