### ISSUE TITLE
Archive civil-rights-complaints repo past issues

### ISSUE THREAD

**Issue by UchMok** [18F/civil-rights#237]
## Description
@UchMok made this repo public and wants to ensure the past issues we had in this repo are archived and exported out of the repo, in case there was anything sensitive..

## Definition of done
- [x] @alexsoble to add exported, closed issues to this [Drive folder](https://drive.google.com/drive/folders/1UyxTDxvXwymDyBv0QJPwZbJdMQ4Ei9A8?usp=sharing)
- [ ] @UchMok to delete closed issues from repo
- [ ]

## Attachments
[title](URL)

**Comment by alexsoble** [comment]
Exported issues JSON added to Drive under Archive folder as `civil-rights-complaints-issues-export.json`.

**Comment by alexsoble** [comment]
@UchMok Upon closer inspection, the export data I prepared earlier was incorrect — it was an export of open issues, not closed ones.

I fixed the export query and wrote a script to handle GitHub's API pagination. The new, correct data export is uploaded in the Archive folder as `closed-civil-rights-complaints-issues-export.json`.

**Comment by alexsoble** [comment]
@UchMok That said, when you have a minute, please double-check the data export to make sure it's what we want. The best way to double check is to look for the "title" and "body" fields in the JSON file.
