### ISSUE TITLE
Technically on board Alex [7/1-7/3]

### ISSUE THREAD

**Issue by UchMok** [18F/civil-rights#243]
## Definition of done
- [x] Acquia cloud account
- [x] Acquia 2 factor enabled
- [x] Add RSA pub key
- [x] Added to our GitHub team
- [x] Pull the codebase locally
- [x] Go over upcoming tasks

**Comment by LindsayYoung** [comment]
Got though a lot today, now Darren, Alex and I all have a copy of the codebase locally
ヘ( ^o^)ノ＼(^_^ )

**Comment by alexsoble** [comment]
Wooohooo!! Thank you for the wonderful technical onboarding @LindsayYoung!! 🎇✨🎇
