### ISSUE TITLE
Reach out to JMD about single sign on integration

### ISSUE THREAD

**Issue by UchMok** [18F/civil-rights#245]
## Description
Give JMD a heads up that we want to integrate with their ADFS single sign on service, answer any of their questions see if they need anything from us and hopefully get auth going on environments.

Can we get the 18F team need to have a DOJ login accounts?

## Definition of done
- [ ]
- [ ]
- [ ]

## Notes
This conversation is getting them ready for 18F/crt-portal#14

Here are the instructions on our side https://docs.acquia.com/site-factory/manage/sso/

Here is the module we should already have in our distro https://www.drupal.org/project/simplesamlphp_auth

**Comment by LindsayYoung** [comment]
This conversation is getting them ready for https://github.com/18F/crt-portal/issues/14
Here are the instructions on our side https://docs.acquia.com/site-factory/manage/sso/
Here is the module we should already have in our distro https://www.drupal.org/project/simplesamlphp_auth

We need to work with JMD on configuration.
