### ISSUE TITLE
Import ISL (CSV) to GitHub as issues

### ISSUE THREAD

**Issue by UchMok** [18F/civil-rights#250]
## Definition of done
- [ ] Format [ISL](https://docs.google.com/spreadsheets/d/1zHz47lbzQ7OdDE_0rTrnPaicZhNrfxotgjrq1mZTiHY/edit#gid=2009918637) for CSV import (Epic, Title, Description, label)
- [ ] Add Story list (thin slice, next, later releases) as issues to GH repo CRT-portal

## Attachments
[title](URL)

**Comment by alexsoble** [comment]
@UchMok I mentioned yesterday that the import script threw errors for a few stories, ID #s below:

```
11, 19, 22, 23, 24
```

Please double-check these; you may need to add these stories to GitHub as issues manually.
