### ISSUE TITLE
Schedule form feedback  sessions w Public deep dive group

### ISSUE THREAD

**Issue by UchMok** [18F/civil-rights#251]
## Definition of done
- [x] Daisy (Friday)
- [x] Tulip (haven't heard back)
- [x] Daffodil (next Friday August 2) need time
- [x] Jasmine (next Tuesday Jul 30)
- [x] Clover (next Wednesday Jul 31)
- [x] Lavender (next Tuesday Jul 30)

## Attachments
[title](URL)

**Comment by Jacklynn** [comment]
Sent a follow up for Tulip & Daffodil yesterday. Haven't heard back
