### ISSUE TITLE
Investigate putting a feedback banner on CRT website

### ISSUE THREAD

**Issue by Jacklynn** [18F/civil-rights#263]
## Description
Our team would like to elicit feedback from the Public by posting a banner on the DOJ CRT website. Example: https://findtreatment.samhsa.gov/

## Definition of done
- [ ] Get clearance from @danielhyi /Kathy/FO
- [ ] Design the banner experience
- [ ]

**Comment by UchMok** [comment]
@danielhyi do you know if this is a possible avenue for us to gather feedback?

**Comment by UchMok** [comment]
@Jacklynn to follow up w/ SAMHSA team to see if they have to get PRA clearance in order to post the banner

**Comment by Jacklynn** [comment]
Allison said the SAMSHA team didn’t get clearance because there is PRA guidance that says `Open-ended requests for comments or feedback` doesn’t require PRA clearance https://pra.digital.gov/about/ (which I also believed was the case)
