### ISSUE TITLE
Reach out to NYC Human Rights form people for usability advice 

### ISSUE THREAD

**Issue by AvivaOskow** [18F/civil-rights#264]
## Definition of done
- [x] Set up meeting
- [x] Have interview
- [x] Thanks you and follow up

## Attachments
[title](URL)

**Comment by AvivaOskow** [comment]
Meeting in person Wednesday for design IRL and will follow up.

Will also make a call for volunteer user interview participants at the same event,

**Comment by Jacklynn** [comment]
Monday @ 2:30 EST - folks welcome to attend!

**Comment by AvivaOskow** [comment]
Notes here
https://docs.google.com/document/d/1eMFdWOnlLUHJBt1dUx9BnWepz4Azm9yLdp7woFLWlTs/edit#
