### ISSUE TITLE
Investigate user testing services

### ISSUE THREAD

**Issue by Jacklynn** [18F/civil-rights#266]
## Description
Like usertesting.com which 18F has an ATO agreement with

## Definition of done
- [x] @UchMok to talk to front office (@danielyi ) around rules about incentive/compensation and if this will affect our PRA submission
- [ ] @ominina to revisit 'policy for user testing compensation' w/ Corey and GSA
- [ ]

## Attachments
Other background info
[Paying Incentives for Federal User Research](https://www.usability.gov/how-to-and-tools/methods/recruiting-usability-test-participants.html)
[Recruiting Usability Test Participants](https://www.usability.gov/how-to-and-tools/methods/recruiting-usability-test-participants.html)

**Comment by Jacklynn** [comment]
Met with Laura to talk about how this worked for them (they used it about 1 year ago:
- Overall happy with service
- Was really good at recruiting, which is why the used the service. Can recruit around technical skills/setup (ex: Chrome browser) and demographics (ex: income)
- She believed it cost about $100/per user. But if you received a 'bad test' they were really good about allowing you to reject the test and they'd find a new participant to test with 
- Allows unmoderated and moderated sessions
--> As a facilitation note for unmoderated sessions, people were bad at reading directions and she said you had to make it really really clear and concise what you wanted them to do

**Comment by UchMok** [comment]
@UchMok to meet with @ominina around funding for 'compensating' pubic users

**Comment by ominina** [comment]
@UchMok working on getting information here

**Comment by ominina** [comment]
@UchMok @AvivaOskow @Jacklynn  got official guidance from Corey that we cannot, in any way, pay for users for participating in user research
