### ISSUE TITLE
Design DOJ CRT Feedback request banner experience

### ISSUE THREAD

**Issue by UchMok** [18F/civil-rights#281]
## Description

Our team would like to elicit feedback from the Public by posting a banner on the DOJ CRT website. Example: https://findtreatment.samhsa.gov/

Definition of done
-[ ] drafting the user workflow experience (lo -fi)  
-[ ] sharing back w/ team
-[ ] Drafting hi-fi mock up

## Attachments
[title](URL)

**Comment by AvivaOskow** [comment]
I think this might be the example you meant @UchMok @Jacklynn ?
https://findtreatmentbeta.18f.gov/

The one in the old link is pretty buried

**Comment by AvivaOskow** [comment]
Banner placement options:

*On "How to file a complaint" page*
_We are leaning towards this one, to try to get people who are interested specifically in the complaint process_
![Screen Shot 2019-07-26 at 3.43.18 PM.png](https://images.zenhubusercontent.com/5846f186b9dc3c6220230bf1/09356091-0c87-41a1-9e8e-38a2415903a3)

*On slider on CRT homepage*
_This would be a good place to catch a lot of attention about this work, but we may confuse people and get responses we don't want_
![Screen Shot 2019-07-23 at 6.26.00 PM.png](https://images.zenhubusercontent.com/5846f186b9dc3c6220230bf1/2e1b52e9-ce34-4aff-bae4-abef50ce3bc5)

*above content of all CRT*
![Screen Shot 2019-07-23 at 6.26.11 PM.png](https://images.zenhubusercontent.com/5846f186b9dc3c6220230bf1/4bdd71d2-2e16-487f-95cd-21e3e2bf59b3)

**Comment by UchMok** [comment]
Blocked: Waiting to get confirmation from Melody (DOJ PRA rep) that this does not need PRA clearance
