### ISSUE TITLE
Discuss recruiting public participants who have worked with the DOJ in the past

### ISSUE THREAD

**Issue by Jacklynn** [18F/civil-rights#282]
## Description
Dan mentioned that people who the DOJ have worked with in the past might be willing to give us feedback on improving the process, want to follow up with the team and him to see if we still want to do that. 

It could be a good way to get feedback from someone experiencing a sensitive topic in a more comfortable way for the participant.

## Definition of done
- [x] Discuss with team and/or Dan
- [ ] Ask in shipping new [8/16]
- [ ] @danielhyi to send a follow-up email to section PoCs

## Attachments
[title](URL)

**Comment by UchMok** [comment]
@Jacklynn why blocked?
