### ISSUE TITLE
Send Software Engineer Role Description to Suey

### ISSUE THREAD

**Issue by UchMok** [18F/civil-rights#298]
## Description
" Suey was asking if she can get the position/skill set description for the developer. She’s ready to get someone on board ASAP (though probably contractor). I’ve clarified and that person will be available to get working on dev." - Daniel

## Definition of done
- [x] Draft skill set description for ideal _CRT Intake Product_ Software Developer
- [x] @ominina to share draft and get feedback from Waldo
- [ ] Share draft/review w/ Core team
- [ ] Send to Suey

## Attachments
[18F Example Software Engineer Role Description](https://docs.google.com/document/d/189JTlR-zFNs1BVjKUYLna8DnU95ZSisZ_Gp4V3x2jqA/edit)

**Comment by ominina** [comment]
Waldo has reviewed/added comments and gave it his 👍
