### ISSUE TITLE
Facilitate 'post mortem' retrospective around Acquia BLT

### ISSUE THREAD

**Issue by UchMok** [18F/civil-rights#300]
## Description
Hoping to gain a shared understanding among the tech team and technical stakeholders around our experience (ups/downs) using Acquia BLT

## Definition of done
- [x] schedule meeting w/ core tech team during core pairing time
- [x] Draft PM of BLT experience 
- [x] Share w/ Ben Schwarten, Jake BG, Suey, Gary

## Attachments
[title](URL)

**Comment by Jacklynn** [comment]
Will do this as part of our standing engineering time next week

**Comment by LindsayYoung** [comment]
Meeting held Aug 14,

Postmortem writeup 
https://docs.google.com/document/d/15w2h1R6lm_FbgMdT-f4S4Utir3ev0Ug8QZPXwiMQW4U/edit

One pager on Acquia BLT and Acquia Cloud experlence
https://docs.google.com/document/d/1DxPeIJQzAI0x4B0IWwJGQTOvwiQ4NG5KLDt4DpKhLdI/edit#heading=h.jmjn81mtfaop

Both documents and the earlier Django/Drupal evaluation were emailed out as well.

**Comment by LindsayYoung** [comment]
moving to done opened the issue?
