### ISSUE TITLE
Q: does the DOJ have jurisdiction or can help folks outside the US?

### ISSUE THREAD

**Issue by Jacklynn** [18F/civil-rights#305]
## Description
Do we need to ask for country in the form for contact? Could the DOJ help someone who's experiencing an issue outside the US?

Examples:
- Ability to vote while abroad
- Discrimination while on activity duty outside the US?

(regardless, we can update the form since it's a less common path but want to check this detail_

## Definition of done
- [x] Ask
- [ ] Update form
- [ ]

## Attachments
[title](URL)

**Comment by UchMok** [comment]
Daniel:

Yes, 
- you may have expats who are US citizens who have returned to their country...
- human trafficking 
- very rare
