### ISSUE TITLE
Non-form related design work

### ISSUE THREAD

**Issue by alexsoble** [18F/civil-rights#310]
## Description

Non-form related design work:

How does a user get to the new form? What context do they need leading into it? 
What work can design focus on while dev is catching up with the form?

Ideas:
- Change content on "How to File a Complaint" page on justice.gov/crt
- Pre-from page or any other context
- Post submission page ("What comes next")
- Form letters

- Usability testing plan or guide for after we are done
- How to work with a style guide/ design system

**Comment by Jacklynn** [comment]
Added to the other design co work time  notes
