### ISSUE TITLE
Schedule Public User Interviews [Round 6] for week of August 26

### ISSUE THREAD

**Issue by UchMok** [18F/civil-rights#330]
## Definition of done
- [x] Send blanket email to all participants who have volunteered for recurring feedback
- [x]  Schedule Participants

Hold feedback sessions:
- [x] Clover
- [x] Daisy
- [x] Zinnia

## Attachments
[round 6 discussion guide](https://docs.google.com/document/d/1Zrhgx-sFbyidFPn3NSchjTi7BTyFhJSpWvTXyS5LriY/edit#) - @Jacklynn

**Comment by Jacklynn** [comment]
Started drafting here: https://docs.google.com/document/d/1Zrhgx-sFbyidFPn3NSchjTi7BTyFhJSpWvTXyS5LriY/edit#

**Comment by UchMok** [comment]
@AvivaOskow please add list of interviewed users (code name) to this task
