### ISSUE TITLE
Assign owners to Skills Transfer tasks

### ISSUE THREAD

**Issue by UchMok** [18F/civil-rights#334]
## Definition of done
- [x] schedule internal CRT meeting to discuss skills transfer ownership
- [x] Assign owners to tasks
- [x] Parse out tasks that don't have ownership
- [ ] Shareback w/ core team

## Attachments
[title](URL)

**Comment by alexsoble** [comment]
Update from Daniel — still in flow!

Route to product manager might be tricky. 

May take several weeks. 

@danielhyi to connect with @UchMok about a meeting with 18F Talent Acquisition team.
