### ISSUE TITLE
Draft Network Setting Diagram for Sean (ATO)

### ISSUE THREAD

**Issue by UchMok** [18F/civil-rights#339]
## Description
Need to effectively explain how the app networking is set up.
## Definition of done
- [x] production network
- [x] DOJ local network set up 
- [x] Email CRT + JMD 

## Attachments
[title](URL)

**Comment by LindsayYoung** [comment]
Current and proposed state done, John is outlining local DOJ network set up for development.


https://docs.google.com/presentation/d/1LAyK65xmOUXU0sR9rHY7QuPnlCz1lxoNARen8uQtcaM/edit#slide=id.g47547fa423_6_305
