### ISSUE TITLE
Reach out to sections to observe how they use systems today

### ISSUE THREAD

**Issue by Jacklynn** [18F/civil-rights#343]
## Description
Shadow using system and ask more detailed questions about their process. Got feedback from Bill & Aviva today after deep dive

## Definition of done
- [x] Draft email and send
- [x] HCE -9/19 1-2 EST
- [x] DRS - 9/19 2:45-3:45 EST
- ~SPL - needs reschedule~ new card created

## Attachments
[Draft discussion guide](https://docs.google.com/document/d/1lp1SV3hwgvaG2EhrNecRKak5uwjq0XKqiiLszlGFt-U/edit)

**Comment by UchMok** [comment]
@Jacklynn to add confirmed times/dates to card

**Comment by alexsoble** [comment]
Two scheduled for today! Housing and DRS (Disability Rights).

**Comment by alexsoble** [comment]
Aviva to take notes, all welcome to observe!
