### ISSUE TITLE
Get approved for use of Auth services - Sean Connonie

### ISSUE THREAD

**Issue by UchMok** [18F/civil-rights#347]
## Definition of done
unblocks: https://app.zenhub.com/workspaces/doj-crt-intake-scrum-board-5d03bf56c1c8a35d482eca0f/issues/18f/crt-portal/14
## Attachments
[title](URL)

**Comment by LindsayYoung** [comment]
Ok, Sean needs more details, we can meet tomorrow, Sean is going to tell me what time works for him.

**Comment by alexsoble** [comment]
@LindsayYoung is going to visit Sean in person to get this done!

**Comment by Jacklynn** [comment]
Alex/Lindsay taking a first pass to add more details (Tech folder of the shared drive folder). Hoping to reply back to Sean today. What he needed to escalate the request.

**Comment by LindsayYoung** [comment]
Bill and Darren are giving Sean additional information for the PIA/(single sign on permission)

**Comment by LindsayYoung** [comment]
Heard from Ben that we will need an interconnection security agreement. Ben from JMD emailed us a template. I responded to Sean and John abut the protocol we are interested in using. 

Checked in with Sean and started a email thread with Eric, who was provided earlier as a SSO point of contact. Looped in cloud.gov.

**Comment by Jacklynn** [comment]
Records retention -- Bill to meet with ORMP. will draft something for review

**Comment by LindsayYoung** [comment]
We got a confirmation on SAML from the SSO team. Set up a call with Sean tomorrow.

**Comment by LindsayYoung** [comment]
Lindsay: Connected with Sean, we are doing two of the templates, one for cloud.gov and one for the app. I have reached out to the cloud.gov team and will need their information here: https://docs.google.com/document/d/1ooj2vjWGwak1NLW0VaMxFw_GXbuNR7L5/edit# Then I will send it back to Sean.


Bill is trying to set up a meeting early next week with ORMP to discuss the retention schedule so we can get that information to Sean as well.

**Comment by alexsoble** [comment]
Waiting on JMD. 

During product champions meeting, Gary Wong (Deputy Executive Officer) would be happy to help. If we have 1 or 2 sentences describing what do we need to have happen, he will help!

**TODO**: Check in with Sean and see if Gary should help us! Sean empowered to check in with Gary.

**Comment by LindsayYoung** [comment]
Sean checked in with Gary on 10/14

**Comment by LindsayYoung** [comment]
Sean pinged the ISA team 10/22

**Comment by LindsayYoung** [comment]
Sean submitted ISA requests, one for a cloud.gov integration and one for our app integration.
Ticket # INC000000970328. He has requested the request to be expedited.

**Comment by Jacklynn** [comment]
Bill got the remaining info to Sean. @blaughman to share with Lindsay!
