### ISSUE TITLE
Developer posting feedback from 18F

### ISSUE THREAD

**Issue by Jacklynn** [18F/civil-rights#351]
## Description
Dan posted the dev job posting on slack and would like feedback from the 18F team.

## Definition of done
- [x] Alex/Lindsay to think of questions they might want to ask folks.
- [ ]

## Attachments
[title](URL)

**Comment by Jacklynn** [comment]
Can't talk to them directly but can ask questions

**Comment by alexsoble** [comment]
@LindsayYoung and I developed questions to ask, link here: https://docs.google.com/document/d/1EEo_OeI49TO-yuVk1LoGJ86zuLZQbOCezZGq_DAbSSk/edit#

**Comment by alexsoble** [comment]
Resume review doc with notes and recommendations from me and @LindsayYoung:

https://docs.google.com/spreadsheets/d/18ZIATyV7ZnEar9vcrPuzMBzP_Il-QgaucTWfUAcGl7Q/edit#gid=0
