### ISSUE TITLE
Onboard Lalitha

### ISSUE THREAD

**Issue by UchMok** [18F/civil-rights#359]
## Description
Lalitha joins team as new PM October 1, when Uchenna is OOO.

## Definition of done
- [x] Invite to core meeting - Uchenna
- [x] Schedule meeting with design around end-to-end mockups @AvivaOskow 
- [x] Schedule meeting w/ design around roadmap vs thin slice scope @Jacklynn 
- [x] Schedule meeting w/ engineers around technical vision, history @LindsayYoung @alexsoble 

## Attachments
[title](URL)

**Comment by lalitha-jonnalagadda** [comment]
Moving this card to done since all meetings were scheduled. Thank you all for your help.
