### ISSUE TITLE
Content design review of current form

### ISSUE THREAD

**Issue by Jacklynn** [18F/civil-rights#368]
## Description
We're getting into the text details of the form and I'd love a content review to provide feedback on order, consistency, and language. 

## Definition of done
- [x] Submit Writing lab issue (~3 hours) https://github.com/18F/writing-lab/issues/468
- [ ] Pair & get feedback
- [ ] Update documentation

## Attachments
[title](URL)

**Comment by alexsoble** [comment]
Hoping to schedule next pairing session for this coming Monday.

**Definition of done**: "Acceptable to show to stakeholders".

We can do placeholder content if needed.
