### ISSUE TITLE
Lindsay's DOJ badge expired :(

### ISSUE THREAD

**Issue by Jacklynn** [18F/civil-rights#369]
## Definition of done
- [ ]
- [ ]
- [ ]

## Attachments
[title](URL)

**Comment by LindsayYoung** [comment]
@danielhyi FYI, I went to the badge office and they were missing a form from Jonathan Mayuga, I just emailed him, when he sends that, I should be able to get a badge. I will Try going back to the DOJ office Tomorrow.

**Comment by LindsayYoung** [comment]
IN!!!! Thank you @danielhyi
