### ISSUE TITLE
Access to staging (intake) for sections

### ISSUE THREAD

**Issue by lalitha-jonnalagadda** [18F/civil-rights#388]
## Definition of done
- [x] Bill to provide a list of users (~ 10)
- [x] Lindsay to create and provide logins and PW to individuals

## Attachments
[title](URL)

**Comment by LindsayYoung** [comment]
Sent 11/15/19
See up to date account list for details: https://docs.google.com/spreadsheets/d/1VM5hSsxUgqFM6t51Ejm_EjxnbxLI-pTXF_CVxZJSekQ/edit#gid=0
