### ISSUE TITLE
Onboarding Adam

### ISSUE THREAD

**Issue by lalitha-jonnalagadda** [18F/civil-rights#400]
## Description
Adam joins team as a new engineer on Nov 18

## Definition of done
- [ ] @lalitha-jonnalagadda  Invite Adam to:
  - [x] core meetings
  - [x] documents/drive  
  - [x] zenhub
  - [x] PA shareback doc (describing the thin slice) 
  - [x] Charter
- [ ] Walkthrough vision, roadmap and thin slice @lalitha-jonnalagadda @UchMok 
- [x] Schedule meeting with design around end-to-end mockups @AvivaOskow 
- [x] Schedule meeting w/ design around User research, personas, etc @Jacklynn 
- [x] Schedule meeting w/ engineers around technical vision, history @LindsayYoung @alexsoble 
- [x] create accounts @LindsayYoung 
   - [x] 18F CRT GitHub team (circle and zenhub access are connected to GitHub)
   - [x] GoogleDrive
   - [x] CRT GitHub @dwechsle
   - [x] cloud.gov
## Attachments
[title](URL)

**Comment by alexsoble** [comment]
Adam and Lalitha have time to finish this card scheduled for Weds!
